import { Destination, Trip, User } from '@/types';

// In-memory persistent state across dev server requests
declare global {
  var __mockDb: {
    user: User;
    trips: Trip[];
    destinations: Destination[];
    savedDestinationIds: Set<string>;
  } | undefined;
}

const initialUser: User = {
  id: 'usr_traveler_1',
  name: 'Abhay Pipaliya',
  email: 'traveler@globetrotter.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  bio: 'Passionate globetrotter, photographer, and culture enthusiast exploring hidden gems around the world.',
  homeCity: 'Surat, India',
  currency: 'USD',
  language: 'English',
  role: 'user',
  createdAt: '2026-01-15T00:00:00.000Z',
};

const initialDestinations: Destination[] = [
  {
    id: 'dest_tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    flagEmoji: '🇯🇵',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    costIndex: 3,
    popularityScore: 4.9,
    bestSeason: 'March - May, Oct - Nov',
    avgDailyCost: 160,
    currency: 'JPY',
    description: 'A captivating metropolis blending neon-lit skyscrapers with historic temples and world-class culinary craft.',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'TeamLab Planets', 'Shinjuku Gyoen', 'Akihabara'],
    isSaved: true,
  },
  {
    id: 'dest_paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    flagEmoji: '🇫🇷',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    costIndex: 4,
    popularityScore: 4.8,
    bestSeason: 'April - June, Sept - Nov',
    avgDailyCost: 210,
    currency: 'EUR',
    description: 'The City of Light famed for haute cuisine, timeless haute couture, the Eiffel Tower, and iconic art museums.',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre', 'Notre-Dame', 'Seine Cruise'],
    isSaved: true,
  },
  {
    id: 'dest_rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    flagEmoji: '🇮🇹',
    coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    costIndex: 3,
    popularityScore: 4.8,
    bestSeason: 'May - Sept',
    avgDailyCost: 145,
    currency: 'EUR',
    description: 'An open-air museum overflowing with ancient ruins, Renaissance art, vibrant piazzas, and mouthwatering pasta.',
    highlights: ['Colosseum', 'Vatican City', 'Trevi Fountain', 'Pantheon', 'Trastevere'],
    isSaved: false,
  },
  {
    id: 'dest_bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    flagEmoji: '🇮🇩',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    costIndex: 1,
    popularityScore: 4.7,
    bestSeason: 'April - October',
    avgDailyCost: 65,
    currency: 'IDR',
    description: 'A tropical paradise known for forested volcanic mountains, iconic rice paddies, beaches, and coral reefs.',
    highlights: ['Ubud Monkey Forest', 'Tanah Lot Temple', 'Tegallalang Rice Terraces', 'Seminyak Beach'],
    isSaved: true,
  },
  {
    id: 'dest_barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    flagEmoji: '🇪🇸',
    coverImage: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1200&q=80',
    costIndex: 3,
    popularityScore: 4.7,
    bestSeason: 'May - June, Sept - Oct',
    avgDailyCost: 130,
    currency: 'EUR',
    description: 'A vibrant Mediterranean city renowned for Gaudi architecture, sunny beaches, tapas bars, and Gothic charm.',
    highlights: ['Sagrada Familia', 'Park Guell', 'Gothic Quarter', 'La Boqueria', 'Barceloneta Beach'],
    isSaved: false,
  },
  {
    id: 'dest_newyork',
    name: 'New York City',
    country: 'United States',
    region: 'Americas',
    flagEmoji: '🇺🇸',
    coverImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1200&q=80',
    costIndex: 4,
    popularityScore: 4.9,
    bestSeason: 'Sept - Nov, April - June',
    avgDailyCost: 280,
    currency: 'USD',
    description: 'The city that never sleeps, offering world-class Broadway shows, iconic skylines, and endless cultural diversity.',
    highlights: ['Central Park', 'Times Square', 'Empire State Building', 'High Line', 'Brooklyn Bridge'],
    isSaved: false,
  },
];

const initialTrips: Trip[] = [
  {
    id: 'trip_japan_2026',
    userId: 'usr_traveler_1',
    title: 'Japan Golden Route Discovery',
    description: 'A 10-day cultural journey through ultra-modern Tokyo, tranquil shrines of Kyoto, and street food of Osaka.',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-10-15',
    endDate: '2026-10-25',
    budget: 3200,
    currency: 'USD',
    visibility: 'public',
    shareToken: 'tok_japan_golden_route',
    status: 'upcoming',
    destinationCount: 3,
    destinations: ['Tokyo', 'Kyoto', 'Osaka'],
    createdAt: '2026-02-01T10:00:00.000Z',
    stops: [
      {
        id: 'stop_1',
        tripId: 'trip_japan_2026',
        cityId: 'dest_tokyo',
        cityName: 'Tokyo',
        country: 'Japan',
        stopOrder: 1,
        arrivalDate: '2026-10-15',
        departureDate: '2026-10-19',
        notes: 'Stay near Shinjuku station for easy transit.',
        transportCost: 120,
        accommodationCost: 650,
      },
      {
        id: 'stop_2',
        tripId: 'trip_japan_2026',
        cityId: 'dest_kyoto',
        cityName: 'Kyoto',
        country: 'Japan',
        stopOrder: 2,
        arrivalDate: '2026-10-19',
        departureDate: '2026-10-23',
        notes: 'Take early morning bullet train (Shinkansen).',
        transportCost: 140,
        accommodationCost: 520,
      },
      {
        id: 'stop_3',
        tripId: 'trip_japan_2026',
        cityId: 'dest_osaka',
        cityName: 'Osaka',
        country: 'Japan',
        stopOrder: 3,
        arrivalDate: '2026-10-23',
        departureDate: '2026-10-25',
        notes: 'Dotonbori food tour at night!',
        transportCost: 40,
        accommodationCost: 280,
      },
    ],
  },
  {
    id: 'trip_europe_2026',
    userId: 'usr_traveler_1',
    title: 'Romantic Paris & Italian Heritage',
    description: 'Art, architecture, and culinary delights across Paris, Florence, and ancient Rome.',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    startDate: '2026-11-05',
    endDate: '2026-11-16',
    budget: 4500,
    currency: 'USD',
    visibility: 'private',
    shareToken: 'tok_paris_rome_2026',
    status: 'upcoming',
    destinationCount: 3,
    destinations: ['Paris', 'Florence', 'Rome'],
    createdAt: '2026-02-10T14:30:00.000Z',
    stops: [
      {
        id: 'stop_eu_1',
        tripId: 'trip_europe_2026',
        cityId: 'dest_paris',
        cityName: 'Paris',
        country: 'France',
        stopOrder: 1,
        arrivalDate: '2026-11-05',
        departureDate: '2026-11-09',
        notes: 'Louvre and Eiffel Tower tickets booked in advance.',
        transportCost: 350,
        accommodationCost: 800,
      },
      {
        id: 'stop_eu_2',
        tripId: 'trip_europe_2026',
        cityId: 'dest_rome',
        cityName: 'Rome',
        country: 'Italy',
        stopOrder: 2,
        arrivalDate: '2026-11-09',
        departureDate: '2026-11-16',
        notes: 'Colosseum and Vatican museum walking tours.',
        transportCost: 150,
        accommodationCost: 950,
      },
    ],
  },
  {
    id: 'trip_bali_past',
    userId: 'usr_traveler_1',
    title: 'Tropical Bali Retreat',
    description: 'Relaxing week among Ubud rice terraces, serene yoga sanctuaries, and Seminyak sunset beaches.',
    coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    startDate: '2025-12-01',
    endDate: '2025-12-08',
    budget: 1800,
    currency: 'USD',
    visibility: 'public',
    shareToken: 'tok_bali_retreat',
    status: 'completed',
    destinationCount: 1,
    destinations: ['Bali'],
    createdAt: '2025-11-01T08:00:00.000Z',
  },
];

if (!global.__mockDb) {
  global.__mockDb = {
    user: initialUser,
    trips: initialTrips,
    destinations: initialDestinations,
    savedDestinationIds: new Set(['dest_tokyo', 'dest_paris', 'dest_bali']),
  };
}

export const db = global.__mockDb;
